spring:
  data:
    mongodb:
      uri: mongodb+srv://fmoussa:xgkg10v1F4qo1W7E@cluster0.yy3ajm3.mongodb.net/gayale_transport_dev?retryWrites=true&w=majority&appName=Cluster0
      auto-index-creation: true

logging:
  level:
    root: WARN
    com.gayale.transport: DEBUG

app:
  qrcode:
    base-url: https://truck-transportation-management.onrender.com/tickets/
  security:
    jwt:
      secret: jwtSecretKey
      expiration: 3600000 # 1 hour in milliseconds
      refresh-expiration: 86400000 # 24 hours in milliseconds